export { default as AdminDashboard } from './AdminDashboard'
export { default as AdminContent } from './AdminContent'
export { default as AdminUsers } from './AdminUsers'
export { default as AdminAnalytics } from './AdminAnalytics'
export { default as AdminSettings } from './AdminSettings'
export { default as AcademyForm } from './AcademyForm'
